---
- name: ----- create project yml -----
  file:
   path: "{{ansible_root}}/{{project_name}}.yml"
   state: touch
  tags: [create_prj_yml]

- name: ----- create project role -----
  file:
   path: "{{ansible_root}}/roles/{{project_name}}"
   state: directory
  tags: [create_role]

- name: ----- create 7 directories -----
  file:
   path: "{{ansible_root}}/roles/{{project_name}}/{{item}}"
   state: directory
  loop:
   - tasks
   - vars
   - templates
   - handlers
   - files
   - defaults
   - meta
  tags: [seven_dir]

- name: ----- create main.yml files -----
  file:
   path: "{{ansible_root}}/roles/{{project_name}}/{{item}}/main.yml"
   state: touch
  loop:
   - tasks
   - vars
   - handlers
   - defaults
   - meta
  tags: []
